### ISSUE TITLE
Java Code To establish MySQL DB connection.

### ISSUE THREAD

**Issue by 10thTARDIS** [10thTARDIS/UMSLDataslayers#9]
#Link to example code for establishing DB connection:
https://github.com/BHunter2889/WCWageReimbursementCalculator/blob/master/src/main/java/Classes/WCReimbursementDAO.java

**Comment by BHunter2889** [comment]
Added Methods for Enter() and Exit() to be called when it is determined that a care entered or left the lot/garage. Updates the MySQL table successfully.
